export const event = {
  addEvent: 'Nouvel évènement',
  createEvent: "Créer l'évènement",
  deleteConfirm: {
    cancel: 'Annuler',
    confirm: 'Confirmer',
    header: "Supprimer l'évènement",
    message: 'Êtes-vous sûr de vouloir supprimer cet évènement ?',
  },
  deleteEvent: "Supprimer l'évènement",
  department: 'Départements',
  description: 'Description',
  endAt: 'Fin',
  location: 'Lieu',
  placeholder: {
    department: 'Sélectionner un ou plusieurs départements',
    description: "Description de l'évènement",
    location: "Lieu de l'évènement",
    title: "Titre de l'évènement",
  },
  publicEvent: 'Événement public',
  startAt: 'Début',
  title: 'Titre',
  toast: {
    created: 'Évènement créé avec succès',
    deleted: 'Évènement supprimé avec succès',
    error: 'Une erreur est survenue',
    updated: 'Évènement modifié avec succès',
  },
  updateEvent: "Modifier l'évènement",
}
