name: iut-intranet-local

services:
  postgres:
    extends:
      file: ./postgres.base.yml
      service: postgres
    container_name: iut-intranet-postgres-local
    restart: 'no'
    ports:
      - '5432:5432'
    volumes:
      - ../.cache/db_data_local:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: iut-intranet-minio-local
    restart: 'no'
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ../.cache/minio_data_local:/data

  minio-init:
    image: minio/mc
    container_name: iut-intranet-minio-init-local
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minioadmin minioadmin; do sleep 1; done;
      mc mb --ignore-existing local/iut-intranet-avatars;
      mc anonymous set download local/iut-intranet-avatars;
      "
